# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-07 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(max_length=5)),
                ('branch_name', models.CharField(max_length=30)),
                ('branch_address', models.CharField(max_length=100)),
                ('opening_date', models.DateField(verbose_name='Date of Branch Open')),
            ],
        ),
        migrations.CreateModel(
            name='Compliances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliance_number', models.PositiveIntegerField(verbose_name='Number of Compliance')),
                ('findings_number', models.PositiveIntegerField(verbose_name='Number of Findings')),
                ('rectified_number', models.PositiveIntegerField(verbose_name='Number of Findings rectified')),
                ('compliance_date', models.DateField(verbose_name='Compliance date')),
            ],
        ),
        migrations.CreateModel(
            name='Inspections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_date', models.DateField(verbose_name='base date of the audit')),
                ('start_date', models.DateField(verbose_name='Starting day of the inspection')),
                ('end_date', models.DateField(verbose_name='Ending day of the inspection')),
                ('submission_date', models.DateField(verbose_name='Report submission date')),
                ('inspection_type', models.CharField(choices=[('CM', 'Comprehensive Inspection'), ('SP', 'Special Inspection')], default='CM', max_length=2)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.Branches')),
            ],
        ),
        migrations.AddField(
            model_name='compliances',
            name='inspection_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.Inspections'),
        ),
    ]
