# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-19 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateField(verbose_name='Report submission date')),
                ('gb_finding', models.PositiveIntegerField(default=0, verbose_name='Number of Findings in GB')),
                ('cr_finding', models.PositiveIntegerField(default=0, verbose_name='Number of Findings in Credit')),
                ('fx_finding', models.PositiveIntegerField(default=0, verbose_name='Number of Findings in Froeign Exchange')),
                ('ict_finding', models.PositiveIntegerField(default=0, verbose_name='Number of Findings in ICT')),
            ],
        ),
        migrations.RemoveField(
            model_name='compliances',
            name='findings_number',
        ),
        migrations.RemoveField(
            model_name='compliances',
            name='rectified_number',
        ),
        migrations.RemoveField(
            model_name='inspections',
            name='submission_date',
        ),
        migrations.AddField(
            model_name='compliances',
            name='cr_rect',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of findings rectified - CR'),
        ),
        migrations.AddField(
            model_name='compliances',
            name='fx_rect',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of findings rectified - FX'),
        ),
        migrations.AddField(
            model_name='compliances',
            name='gb_rect',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of findings rectified - GB'),
        ),
        migrations.AddField(
            model_name='compliances',
            name='ict_rect',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of findings rectified - ICT'),
        ),
        migrations.AddField(
            model_name='reports',
            name='inspection_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.Inspections'),
        ),
    ]
